<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FUGQNF4" ignored="0" name="Test" tests="62" failures="5" timestamp="03 Feb 2023 05:40:37 GMT" time="0.4" errors="0">
  <testcase name="test1" time="0.005" classname="org.rerun.Case1"/>
  <testcase name="test2" time="0.002" classname="org.rerun.Case1"/>
  <testcase name="test3" time="0.006" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.004" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.003" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.007" classname="org.rerun.Case1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="org.rerun.Case1">
    <failure type="java.lang.AssertionError" message="expected [accepted] but found [boundry]">
      <![CDATA[java.lang.AssertionError: expected [accepted] but found [boundry]
at org.rerun.Case1.test3(Case1.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.002" classname="org.rerun.Case1"/>
  <testcase name="testa" time="0.001" classname="org.rerun.Case2"/>
  <testcase name="testb" time="0.012" classname="org.rerun.Case2"/>
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.002" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.005" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <failure type="java.lang.AssertionError" message="expected [nation] but found [country]">
      <![CDATA[java.lang.AssertionError: expected [nation] but found [country]
at org.rerun.Case2.testc(Case2.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testc -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.008" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.0" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.0" classname="org.rerun.Case2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Case2.testd(Case2.java:41)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testd -->
  <testcase name="testA" time="0.001" classname="org.rerun.Case3"/>
  <testcase name="testB" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.0" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.002" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.01" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.003" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.003" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.001" classname="org.rerun.Case3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerun.Case3.testB(Case3.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase name="testC" time="0.008" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.002" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.0" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <skipped/>
  </testcase> <!-- testC -->
  <testcase name="testC" time="0.001" classname="org.rerun.Case3">
    <failure type="java.lang.AssertionError" message="expected [secondry] but found [century]">
      <![CDATA[java.lang.AssertionError: expected [secondry] but found [century]
at org.rerun.Case3.testC(Case3.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testC -->
  <testcase name="testD" time="0.001" classname="org.rerun.Case3"/>
</testsuite> <!-- Test -->
